### ISSUE TITLE
表单 options 方法报错。

### ISSUE THREAD

**Issue by jxlwqq** [z-song/laravel-admin#1340]
- Laravel Version: 5.5.17
- PHP Version:7.1
- Laravel-admin: 1.5.5

### Description:
```
 $form->radio('invoice_type', '发票类型')->options([
            '0' => '不需要发票',
            '1' => '增值税普通发票',
            '2' => '增值税专用发票',
            '3' => '稍后提供发票信息'
])->default(0)->rules('required');

```

当时用 options 方法时，会报以下这个错误信息：

```
FatalThrowableError In Builder.php line 518 :

Call to a member function addEagerConstraints() on array
```

**Comment by z-song** [comment]
没有重现你的问题，你看下log跟踪一下异常

**Comment by jxlwqq** [comment]
```
[2017-10-20 16:13:24] local.ERROR: Call to a member function addEagerConstraints() on array {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function addEagerConstraints() on array at /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:518)
[stacktrace]
#0 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(496): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelation(Array, 'mail_status', Object(Closure))
#1 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(464): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelations(Array)
#2 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#3 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(289): Illuminate\\Database\\Eloquent\\Builder->first(Array)
#4 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(319): Illuminate\\Database\\Eloquent\\Builder->find('1', Array)
#5 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/encore/laravel-admin/src/Form.php(950): Illuminate\\Database\\Eloquent\\Builder->findOrFail('1')
#6 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/encore/laravel-admin/src/Form.php(227): Encore\\Admin\\Form->setFieldValue('1')
#7 /Users/jxlwqq/PhpstormProjects/bio360.net/app/Admin/Controllers/EventOrderController.php(47): Encore\\Admin\\Form->edit('1')
#8 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/encore/laravel-admin/src/Layout/Content.php(38): App\\Admin\\Controllers\\EventOrderController->App\\Admin\\Controllers\\{closure}(Object(Encore\\Admin\\Layout\\Content))
#9 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/encore/laravel-admin/src/Admin.php(86): Encore\\Admin\\Layout\\Content->__construct(Object(Closure))
#10 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Encore\\Admin\\Admin->content(Object(Closure))
#11 /Users/jxlwqq/PhpstormProjects/bio360.net/app/Admin/Controllers/EventOrderController.php(48): Illuminate\\Support\\Facades\\Facade::__callStatic('content', Array)
#12 [internal function]: App\\Admin\\Controllers\\EventOrderController->edit('1')
#13 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#14 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('edit', Array)
#15 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Admin\\Controllers\\EventOrderController), 'edit')
#16 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#17 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(645): Illuminate\\Routing\\Route->run()
#18 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/encore/laravel-admin/src/Middleware/Permission.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Encore\\Admin\\Middleware\\Permission->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/encore/laravel-admin/src/Middleware/Bootstrap.php(23): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Encore\\Admin\\Middleware\\Bootstrap->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/encore/laravel-admin/src/Middleware/LogOperation.php(34): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Encore\\Admin\\Middleware\\LogOperation->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/encore/laravel-admin/src/Middleware/Pjax.php(24): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Encore\\Admin\\Middleware\\Pjax->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/encore/laravel-admin/src/Middleware/Authenticate.php(25): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Encore\\Admin\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(647): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#54 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(622): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#55 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(588): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#56 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(577): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#57 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#58 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\\Debugbar\\Middleware\\Debugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#66 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#67 /Users/jxlwqq/PhpstormProjects/bio360.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#68 /Users/jxlwqq/PhpstormProjects/bio360.net/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#69 /Users/jxlwqq/PhpstormProjects/bio360.net/server.php(21): require_once('/Users/jxlwqq/P...')
#70 {main}
"} 
```

**Comment by jxlwqq** [comment]
我把数据库的表字段名称重命名后，就好了，但是再改回原来的字段名，就又不行了。

**Comment by jxlwqq** [comment]
跟这个问题类似：
https://github.com/z-song/laravel-admin/issues/1312

**Comment by z-song** [comment]
根据log提示，加载关系`mail_status`的时候，模型里面的`mail_status`方法返回的数据是数组 而不是Relation

**Comment by jxlwqq** [comment]
这个 mail_status 跟 invoice_type 一样都是 radio 类型的数据。options方法不能传数组？
```
$form->radio('mail_status', '邮寄状态')->options([
                '0' => '未寄出',
                '1' => '已寄出',
                '2' => '已签收',
            ]);
```
我把表字段 mail_status 重命名成mail_status_d，然后 radio 也改成 $form->radio('mail_status_d', '邮寄状态') 就正常了，改回 mail_status 就又报错了。

**Comment by jxlwqq** [comment]
http://v.youku.com/v_show/id_XMzA5ODIzNjM0NA==.html?spm=a2h3j.8428770.3416059.1

我上传了个视频。把我的操作录下来了

**Comment by jxlwqq** [comment]
http://v.youku.com/v_show/id_XMzA5ODI3MjUwMA==.html?spm=a2h3j.8428770.3416059.1

清晰版的。@z-song

**Comment by z-song** [comment]
模型里面有这个字段相关的方法么

**Comment by jxlwqq** [comment]
有的，卧槽。。。重名了。
```
static public function mail_status()
    {
        return [
            '0' => '未寄出',
            '1' => '已寄出',
            '2' => '已签收',
        ];
    }
```

我把这个写成一个静态方法了。。。
谢谢。
