### ISSUE TITLE
HasMany中的字段配置了rules报错

### ISSUE THREAD

**Issue by never615** [z-song/laravel-admin#2711]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#
1.6.6
### Description:
```
class HasMany extends Field
{
    public function getValidator(array $input)
    {
............

        foreach ($rules as $column => $rule) {
            foreach (array_keys($input[$this->column]) as $key) {
                $newRules["{$this->column}.$key.$column"] = $rule;
                //**下面这行报错,错误日志如下** $input[$this->column][$key][$column] 打印处理出来对应的是一个表单字段的value
                if (isset($input[$this->column][$key][$column])) {
                    foreach ($input[$this->column][$key][$column] as $vkey => $value) {
                        $newInput["{$this->column}.$key.{$column}$vkey"] = $value;
                    }
                }
            }
        }

        return Validator::make($newInput, $newRules, $this->validationMessages, $attributes);
    }
}
```

```
Invalid argument supplied for foreach() {"exception":"[object] (ErrorException(code: 0): Invalid argument supplied for foreach() at /app/back_end/easy_admin/integration/packages/encore/laravel-admin/src/Form/Field/HasMany.php:165)
[stacktrace]
#0 /app/back_end/easy_admin/integration/packages/encore/laravel-admin/src/Form/Field/HasMany.php(165): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Invalid argumen...', '/app/back_end/e...', 165, Array)
#1 /app/back_end/easy_admin/integration/packages/encore/laravel-admin/src/Form.php(1119): Encore\\Admin\\Form\\Field\\HasMany->getValidator(Array)
#2 /app/back_end/easy_admin/integration/packages/encore/laravel-admin/src/Form.php(550): Encore\\Admin\\Form->validationMessages(Array)
#3 /app/back_end/easy_admin/integration/packages/mallto/laravel-admin-enhance/src/Controllers/Base/ModelForm.php(35): Encore\\Admin\\Form->update('7')
```

### Steps To Reproduce:
在hasMany中的表单字段调用`rules()`添加'required'规则即可

应该同https://github.com/z-song/laravel-admin/issues/2474

**Comment by z-song** [comment]
提交了修复  更新到v1.6.7
