### ISSUE TITLE
pjax 500 error in 1.7.9

### ISSUE THREAD

**Issue by nosun** [z-song/laravel-admin#4404]
- Laravel Version: 6.2
- PHP Version:7.3
- Laravel-admin: 1.7.9

### Description:

from 表单 提交， pjax 执行过程中服务器 500 错误，数据可以正常存储。

错误日志为：
```
[2020-02-27 12:02:06] local.ERROR: Return value of Symfony\Component\DomCrawler\Crawler::createSubCrawler() must be an instance of Symfony\Component\DomCrawler\object, instance of Symfony\Component\DomCrawler\Crawler returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of Symfony\\Component\\DomCrawler\\Crawler::createSubCrawler() must be an instance of Symfony\\Component\\DomCrawler\\object, instance of Symfony\\Component\\DomCrawler\\Crawler returned at /Users/nosun/Sites/pijiu/vendor/symfony/dom-crawler/Crawler.php:1215)
[stacktrace]
#0 /Users/nosun/Sites/pijiu/vendor/symfony/dom-crawler/Crawler.php(969): Symfony\\Component\\DomCrawler\\Crawler->createSubCrawler(NULL)
#1 /Users/nosun/Sites/pijiu/vendor/symfony/dom-crawler/Crawler.php(189): Symfony\\Component\\DomCrawler\\Crawler->filterRelativeXPath('descendant-or-s...')
#2 /Users/nosun/Sites/pijiu/vendor/symfony/dom-crawler/Crawler.php(169): Symfony\\Component\\DomCrawler\\Crawler->addHtmlContent('<!DOCTYPE html>...', 'utf-8')
#3 /Users/nosun/Sites/pijiu/vendor/symfony/dom-crawler/Crawler.php(123): Symfony\\Component\\DomCrawler\\Crawler->addContent('<!DOCTYPE html>...')
#4 /Users/nosun/Sites/pijiu/vendor/symfony/dom-crawler/Crawler.php(72): Symfony\\Component\\DomCrawler\\Crawler->add('<!DOCTYPE html>...')
#5 /Users/nosun/Sites/pijiu/vendor/encore/laravel-admin/src/Middleware/Pjax.php(90): Symfony\\Component\\DomCrawler\\Crawler->__construct('<!DOCTYPE html>...')
#6 /Users/nosun/Sites/pijiu/vendor/encore/laravel-admin/src/Middleware/Pjax.php(35): Encore\\Admin\\Middleware\\Pjax->filterResponse(Object(Illuminate\\Http\\Response), '#pjax-container')
#7 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Encore\\Admin\\Middleware\\Pjax->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#8 /Users/nosun/Sites/pijiu/vendor/encore/laravel-admin/src/Middleware/Authenticate.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#9 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Encore\\Admin\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#24 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#25 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#26 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#27 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#28 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /Users/nosun/Sites/pijiu/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Users/nosun/Sites/pijiu/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Cors\\HandlePreflight->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#43 /Users/nosun/Sites/pijiu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#44 /Users/nosun/Sites/pijiu/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#45 /Users/nosun/.composer/vendor/laravel/valet/server.php(147): require('/Users/nosun/Si...')
#46 {main}
"} 
```

**Comment by nosun** [comment]
测试了 1.7.8， 是好的。

**Comment by mini443** [comment]
我的1.7.9  1.7.11  都不行

**Comment by z-song** [comment]
@nosun @mini443 用phpinfo查看一下php版本

**Comment by mini443** [comment]
> @nosun @mini443 用phpinfo查看一下php版本

7.2.28

**Comment by mini443** [comment]
> @nosun @mini443 用phpinfo查看一下php版本



> 测试了 1.7.8， 是好的。

好像是因为php的严格类型检测 。1207行 object 改为 ：self  还有965行 也改为 :self 就可以了

**Comment by z-song** [comment]
object类型的type hint在php 7.2以上版本是支持的，唯一的原因就是php版本低于7.2

可以在这里看到各个版本的运行结果 https://3v4l.org/nlGUq

**Comment by nosun** [comment]
检查了一下，php 版本是  PHP Version 7.1.25，那确实和php 版本有关系。

**Comment by mini443** [comment]
> object类型的type hint在php 7.2以上版本是支持的，唯一的原因就是php版本低于7.2
> 
> 可以在这里看到各个版本的运行结果 https://3v4l.org/nlGUq

laravel-admin-ext/reporter  大佬 ，这个插件怎么不更新了。
