### ISSUE TITLE
Laravel 9 Filesystem

### ISSUE THREAD

**Issue by i838847058** [z-song/laravel-admin#5574]
- Laravel Version: 9.10.1
- PHP Version: 8.0.18
- Laravel-admin: 1.8.14

## Message：
```
League\Flysystem\Filesystem::has(): Argument #1 ($location) must be of type string, null given, called in /mnt/php/ElectricHomeAdmin/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php on line 174 {"userId":1,"exception":"[object] (TypeError(code: 0): League\\Flysystem\\Filesystem::has(): Argument #1 ($location) must be of type string, null given, called in /mnt/php/ElectricHomeAdmin/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php on line 174 at /mnt/php/ElectricHomeAdmin/vendor/league/flysystem/src/Filesystem.php:44)
```
## Code：
```
        $grid = new Grid(new Brands());
        $grid->column('logo_img_url', __('图标（500×500px）'))->image();
```
## Result：
```
[stacktrace]
#0 /mnt/php/ElectricHomeAdmin/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(174): League\\Flysystem\\Filesystem->has()
#1 /mnt/php/ElectricHomeAdmin/vendor/encore/laravel-admin/src/Form/Field/UploadField.php(500): Illuminate\\Filesystem\\FilesystemAdapter->exists()
#2 /mnt/php/ElectricHomeAdmin/vendor/encore/laravel-admin/src/Form/Field/File.php(137): Encore\\Admin\\Form\\Field\\File->destroy()
#3 /mnt/php/ElectricHomeAdmin/vendor/encore/laravel-admin/src/Form/Field/Image.php(42): Encore\\Admin\\Form\\Field\\File->uploadAndDeleteOriginal()
#4 /mnt/php/ElectricHomeAdmin/vendor/encore/laravel-admin/src/Form.php(933): Encore\\Admin\\Form\\Field\\Image->prepare()
#5 /mnt/php/ElectricHomeAdmin/vendor/encore/laravel-admin/src/Form.php(337): Encore\\Admin\\Form->prepareInsert()
#6 /mnt/php/ElectricHomeAdmin/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(30): Encore\\Admin\\Form->Encore\\Admin\\{closure}()
#7 /mnt/php/ElectricHomeAdmin/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(462): Illuminate\\Database\\Connection->transaction()
#8 /mnt/php/ElectricHomeAdmin/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Illuminate\\Database\\DatabaseManager->__call()
#9 /mnt/php/ElectricHomeAdmin/vendor/encore/laravel-admin/src/Form.php(346): Illuminate\\Support\\Facades\\Facade::__callStatic()
#10 /mnt/php/ElectricHomeAdmin/vendor/encore/laravel-admin/src/Controllers/HasResourceActions.php(26): Encore\\Admin\\Form->store()
#11 /mnt/php/ElectricHomeAdmin/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): 

......
```

**Comment by altwei** [comment]
这么高端吗，都上 laravel 9 了

**Comment by i838847058** [comment]
> 
不是说9版本是LTS吗 很多新版本的包都要求8.0了 难道不上吗。。。
还是说都通过降版本解决问题

**Comment by iamB0rgy** [comment]
Will this work on Laravel 9* and PHP 8*?

**Comment by nebtden** [comment]
> Will this work on Laravel 9* and PHP 8*?

I used laravel 9 but it looks like not work

**Comment by altwei** [comment]
> > Will this work on Laravel 9* and PHP 8*?
> 
> I used laravel 9 but it looks like not work

It hasn't been updated in a long time
