### ISSUE TITLE
Class "Symfony\Component\DomCrawler\Crawler" not found in file 

### ISSUE THREAD

**Issue by Mte90** [z-song/laravel-admin#5797]
- Laravel Version: 9.19
- PHP Version: 8.1
- Laravel-admin: 1.8.19

### Description:

I get this error on saving some fields:

```
Error: Class "Symfony\Component\DomCrawler\Crawler" not found in file /home/www/stuffvendor/encore/laravel-admin/src/Middleware/Pjax.php on line 90

#0 /home/www/stuffvendor/encore/laravel-admin/src/Middleware/Pjax.php(35): Encore\Admin\Middleware\Pjax->filterResponse()
#1 /home/www/stuffvendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\Admin\Middleware\Pjax->handle()
#2 /home/www/stuffvendor/encore/laravel-admin/src/Middleware/Authenticate.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#3 /home/www/stuffvendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\Admin\Middleware\Authenticate->handle()
#4 /home/www/stuffvendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#5 /home/www/stuffvendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#6 /home/www/stuffvendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#7 /home/www/stuffvendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
```

Adding the package fix the issue `composer require symfony/dom-crawler`

**Comment by secelite** [comment]
Can you reproduce the issue in a clean setup? This package is already a [requirement in the laravel-admin composer.json](https://github.com/z-song/laravel-admin/blob/v1.8.19/composer.json#L16).

**Comment by Mte90** [comment]
In my case the version on the composer that stopped the error is `"symfony/dom-crawler": "^6.3",`

**Comment by hasy2415** [comment]
is it resolved?
