### ISSUE TITLE
BadMethodCallException In Macroable.php line 87 Method Illuminate\Support\Str::pluck does not exist.

### ISSUE THREAD

**Issue by Daniel-ccx** [z-song/laravel-admin#5844]
- Laravel Version: 9.30.1
- PHP Version: 8.1.23
- Laravel-admin: 1.8.

### Description:
<img width="596" alt="image" src="https://github.com/z-song/laravel-admin/assets/5927124/c92bf319-44ae-43a4-a730-f83cb0d2cbb0">
。。。是版本不对应吗？生产环境也突然出了这个错，没头绪了

### Steps To Reproduce:
 BadMethodCallException In Macroable.php line 87 :
  Method Illuminate\Support\Str::pluck does not exist.

#0 [internal function]: Illuminate\Support\Str::__callStatic('pluck', Array)
#1 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/encore/laravel-admin/src/Grid/Column.php(671): call_user_func_array(Array, Array)
#2 [internal function]: Encore\Admin\Grid\Column->Encore\Admin\Grid\{closure}('2', Object(Encore\Admin\Grid\Column))
#3 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/encore/laravel-admin/src/Grid/Column.php(518): call_user_func_array(Object(Closure), Array)
#4 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/encore/laravel-admin/src/Grid/Column.php(567): Encore\Admin\Grid\Column->callDisplayCallbacks('2', 0)
#5 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/encore/laravel-admin/src/Grid.php(570): Encore\Admin\Grid\Column->fill(Array)
#6 [internal function]: Encore\Admin\Grid->Encore\Admin\{closure}(Object(Encore\Admin\Grid\Column), 4)
#7 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(560): array_map(Object(Closure), Array, Array)
#8 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(719): Illuminate\Support\Arr::map(Array, Object(Closure))
#9 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/encore/laravel-admin/src/Grid.php(573): Illuminate\Support\Collection->map(Object(Closure))
#10 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/encore/laravel-admin/src/Grid.php(930): Encore\Admin\Grid->build()
#11 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/encore/laravel-admin/src/Layout/Column.php(100): Encore\Admin\Grid->render()
#12 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/encore/laravel-admin/src/Layout/Row.php(80): Encore\Admin\Layout\Column->build()
#13 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/encore/laravel-admin/src/Layout/Content.php(215): Encore\Admin\Layout\Row->build()
#14 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/encore/laravel-admin/src/Layout/Content.php(308): Encore\Admin\Layout\Content->build()
#15 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Encore\Admin\Layout\Content->render()
#16 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\Http\Response->setContent(Object(Encore\Admin\Layout\Content))
#17 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(833): Illuminate\Http\Response->__construct(Object(Encore\Admin\Layout\Content), 200, Array)
#18 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(802): Illuminate\Routing\Router::toResponse(Object(Illuminate\Http\Request), Object(Encore\Admin\Layout\Content))
#19 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Encore\Admin\Layout\Content))
#20 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/encore/laravel-admin/src/Middleware/Permission.php(46): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\Admin\Middleware\Permission->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/encore/laravel-admin/src/Middleware/Bootstrap.php(15): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\Admin\Middleware\Bootstrap->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/encore/laravel-admin/src/Middleware/LogOperation.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\Admin\Middleware\LogOperation->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/encore/laravel-admin/src/Middleware/Pjax.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\Admin\Middleware\Pjax->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/encore/laravel-admin/src/Middleware/Authenticate.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Encore\Admin\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#39 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#46 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#47 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#48 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#49 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#50 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#51 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/app/Http/Middleware/TraceRecordMiddleware.php(20): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\Http\Middleware\TraceRecordMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#69 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#70 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#71 /Users/cuichangxi/Public/projects/douguagua/dgg-api-admin/vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php(16): require_once('/Users/cuichang...')
#72 {main}

**Comment by Daniel-ccx** [comment]
$grid->column('roles', trans('admin.roles'))->pluck('name')->label();

roles被重写了....
